### ISSUE TITLE
Exact aiohttp version

### ISSUE THREAD

**Issue by imbolc** [klen/aioauth-client#28]
Is there any reasons do not use `aiohttp>=1.0.5`? It's not convenient to install it with `--no-deps` switch :)

**Comment by offero** [comment]
Yeah, you should use min/max versions if you know of an incompatibility, otherwise don't use strict versions  in setup.py files. requirements.txt files are usually for environment setup and application installation, and less for library use.

**Comment by benjolitz** [comment]
Hi,

This issue affects me. I've opted to ignore this library in favor of using requests_oauth and simply catching exceptions and using the synchronous library to refresh our oauth tokens.

I would love to use this library, but seeing this issue is from last year has convinced me this software has no future and no maintainer.

That makes me sad.

**Comment by calston** [comment]
Anyone out there?

**Comment by butla** [comment]
So I guess this is fixed with the recent commits. @imbolc You can finally close this :)
